### ISSUE TITLE
2017 Oct weekdays displayed wrongly

### ISSUE THREAD

**Issue by CapriceLi** [jkuri/ng-daterangepicker#40]
Hi, I really like this useful tool you developed. 

But when I am using it in my project, occasionally I found the weekdays displayed was wrong.

To be specifically, 2017 Oct 1st should be Sunday, but appears to be Monday in ng-daterangepicker.

Can you review and make updates against this defect? Because I will feel really sorry to abort this very significant extension in my project.
<img width="499" alt="2017-11-08 18 30 58" src="https://user-images.githubusercontent.com/24730954/32544296-b0182d38-c43d-11e7-8203-c04439872b37.png">

**Comment by jkuri** [comment]
hi @CapriceLi thanks for the report. I will fix that during the weekend, if you find solution before please provide a PR. I am very busy currently and cannot do it before weekend.

**Comment by CapriceLi** [comment]
Hi Jan,

Sure. I’ll see what I can do.

Thank you.

**Comment by CapriceLi** [comment]
Hi Jan,

As I noticed, you have approved my pr and merging has been automate completed. I'm not sure about the process, but will you release a latest package in npm so that i can update?

**Comment by jkuri** [comment]
I did already. check version `0.3.0`. thanks for the fix!

**Comment by CapriceLi** [comment]
With pleasure~

**Comment by CapriceLi** [comment]
Hi,

Sorry to bother again, but when I tried to build my project with the updated ng-daterangepicker, it failed and the error message is like

'ERROR in Unexpected value 'NgDateRangePickerModule in /Users/Caprice/Documents/xxxxx/node_modules/ng-daterangepicker/lib/src/ng-daterangepicker/ng-daterangepicker.module.d.ts' imported by the module 'AppModule in /Users/Caprice/Documents/xxxxx/src/app/app.module.ts'. Please add a @NgModule annotation.'

I'm not very sure, but is it something wrong occurs at your side?

Looking forward to your response.

**Comment by jkuri** [comment]
yes I accidentaly published `.d.ts` files, please try again in 5min.

**Comment by jkuri** [comment]
okay try now please

**Comment by jkuri** [comment]
please use `@angular/cli` or `@ngtools/webpack`.

**Comment by CapriceLi** [comment]
well.. I am using @angular/cli to scaffold my project right now. What do you exactly mean by using @angular/cli?

**Comment by jkuri** [comment]
not sure why it is then looking for template file while it is already compiled and inlined. tought you are using systemjs. can you show me how do you import the module?

**Comment by CapriceLi** [comment]
sure.
test.component.ts
`import { NgDateRangePickerOptions } from 'ng-daterangepicker';`

app.module.ts
```
import { NgDateRangePickerModule } from 'ng-daterangepicker';
..
@NgModule({
...,
imports: [...,NgDateRangePickerModule,]
```

It's basically the same as when I used version 0.2.0

**Comment by CapriceLi** [comment]
Hi,

I misunderstood a little bit of your last comment. For your information, I'm not using system.js. I tried to implement 0.3.1 package on other projects, but the results seems the same.

So.. are you gonna fix this?

**Comment by jkuri** [comment]
hi @CapriceLi. sure I will check whats going on, maybe the module is not compiled alright.

**Comment by jkuri** [comment]
@CapriceLi I solved it by adding
```json
"paths": {
  "@ng-daterangepicker/*": ["../node_modules/ng-daterangepicker/src/ng-daterangepicker"]
}
```
to `src/tsconfig.app.json` configuration.

Then I used
```ts
// app.module.ts
import { NgDateRangePickerModule } from '@ng-daterangepicker/ng-daterangepicker.module';
// app.component.ts
import { NgDateRangePickerOptions } from '@ng-daterangepicker/ng-daterangepicker.component';
```
as imports.

I am attaching sample `angular-cli` project for reference. I hope that helps!
[proj.zip](https://github.com/jkuri/ng-daterangepicker/files/1479047/proj.zip)

**Comment by CapriceLi** [comment]
Perfectly works now, thank you so much!
